# Generated by Django 4.0 on 2021-12-13 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=200)),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_name', models.CharField(max_length=45)),
                ('age', models.PositiveIntegerField()),
                ('owners_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='owners.owners')),
            ],
        ),
    ]
