# Generated by Django 4.0 on 2021-12-13 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dogs',
            old_name='owners_id',
            new_name='owners',
        ),
    ]
